language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t julianleweling/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true julianleweling/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "Docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-1-660973569763"
  bucket_path: "Docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY