language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t julianleweling/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true julianleweling/docker-react npm run test
